---
title: "Diagnostic socio-démographique"
author: "Cantien Collinet"
date: "`r format(Sys.time(), '%A %d %B %Y')`"
output:
  html_document: default
  pdf_document: default
  word_document: default
lang: fr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(tidyverse)
library(scales)
library(gt)
library(sf)

# Télécharger
# IRIS du département : https://geoservices.ign.fr/irisge

# À RENSEIGNER :
codes_unite_urbaine <- c(
  "00760" # Unité urbaine de Lyon
)
codes_epci <- c(
  "200046977" # Métropole de Lyon
)
codes_insee_com <- c(
  "69266" # Villeurbanne
)
codes_IRIS_zone <- c(
  "692661001",
  "692661204",
  "692661201",
  "692660103",
  "692660902",
  "692660903",
  "692661002"
)
nom_zone <- "Zone d'étude"
nom_comm <- "Villeurbanne"
nom_unite_urbaine <- "Unité urbaine"
nom_epci <- "Métropole de lyon"
nom_dep <- "Département"

# Niveaux géographiques à afficher, parmi :
# geo_levels = c("NAT", "DEP", "EPCI", "GROUP_COM", "COM", "GROUP_IRIS", "IRIS")
geo_levels = c("NAT", "EPCI", "COM", "GROUP_IRIS")

# FIN de À RENSEIGNER

source("source/functions/extract_dep_and_com.R")
codes_dep <- extract_codes_dep(codes_IRIS_zone)
codes_com <- extract_codes_com(codes_IRIS_zone)
#codes_insee_com <- extract_codes_insee_com(codes_IRIS_zone)
source("source/functions/data_import.R")
```

## Zone d'étude

La zone d'étude est constituée par les IRIS dont les codes sont : `r codes_IRIS_zone`.

## Démographie

```{r demographie, echo=FALSE}
# Traitements à faire
compute_stats_demog = function(data) {
  data %>% summarise(
    # Part de 0-14 ans
    P17_POP0014 = sum(P17_POP0014, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part de 15-29 ans
    P17_POP1529 = sum(P17_POP1529, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part de 30-44 ans
    P17_POP3044 = sum(P17_POP3044, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part de 45-59 ans
    P17_POP4559 = sum(P17_POP4559, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part de 60-74 ans
    P17_POP6074 = sum(P17_POP6074, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part de 75 ans et plus
    P17_POP75P = sum(P17_POP75P, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part d'hommes
    P17_POPH = sum(P17_POPH, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Part de femmes
    P17_POPF = sum(P17_POPF, na.rm = TRUE) / sum(P17_POP, na.rm = TRUE),
    # Population totale (2017)
    P17_POP = sum(P17_POP)
  ) %>%
  mutate(P17_POP = as.integer(P17_POP))
}

# Import des données
demog_IRIS <- import_demographie_departement_IRIS() %>%
  full_join(import_epci_COM(), by = "INSEE_COM") %>%
  full_join(import_departement_IRIS(), by = c("CODE_IRIS", "INSEE_COM"))

# Apply computations to geo levels
source("source/functions/apply_computations.R")
demog_stats <- apply_computations(
  demog_IRIS,
  compute_stats_demog,
  geo_levels
)

# Tableau "Âges"
demog_stats %>%
  select(
    id,
    P17_POP0014,
    P17_POP1529,
    P17_POP3044,
    P17_POP4559,
    P17_POP6074,
    P17_POP75P,
    P17_POP
  ) %>%
  rename(
    " " = id,
    " 0-14 ans" = P17_POP0014,
    "15-29 ans" = P17_POP1529,
    "30-44 ans" = P17_POP3044,
    "45-59 ans" = P17_POP4559,
    "60-74 ans" = P17_POP6074,
    "75+ ans" = P17_POP75P,
    "Pop. totale" = P17_POP
  ) %>%
  gt() %>%
  tab_header(title = "Âges", subtitle = md("&nbsp;")) %>%
  fmt_percent(
    columns = 2:7,
    decimals = 0,
    pattern = "{x}",
    incl_space = TRUE,
    locale = "fr_FR"
  ) %>%
  fmt_number(
    columns = 8,
    decimals = 0,
    locale = "fr_FR"
  ) %>%
  tab_source_note(
    source_note = "Données : Insee, 2017."
  )

# Tableau "Population"
demog_stats %>%
  select(
    id,
    P17_POPH,
    P17_POPF,
    P17_POP
  ) %>%
  rename(
    " " = id,
    "Hommes" = P17_POPH,
    "Femmes" = P17_POPF,
    "Pop. totale" = P17_POP
  ) %>%
  gt() %>%
  tab_header(title = "Sexes", subtitle = md("&nbsp;")) %>%
  fmt_percent(
    columns = 2:3,
    decimals = 0,
    pattern = "{x}",
    incl_space = TRUE,
    locale = "fr_FR"
  ) %>%
  fmt_number(
    columns = 4,
    decimals = 0,
    locale = "fr_FR"
  ) %>%
  tab_source_note(
    source_note = "Données : Insee, 2017."
  )
```

## Socio-économie

```{r csp, echo=FALSE}
# Traitement à faire
compute_stats_csp = function(data) {
  data %>% summarise(
    C17_POP15P_CS1 = sum(C17_POP15P_CS1, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS2 = sum(C17_POP15P_CS2, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS3 = sum(C17_POP15P_CS3, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS4 = sum(C17_POP15P_CS4, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS5 = sum(C17_POP15P_CS5, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS6 = sum(C17_POP15P_CS6, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS7 = sum(C17_POP15P_CS7, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE),
    C17_POP15P_CS8 = sum(C17_POP15P_CS8, na.rm = TRUE) / sum(C17_POP15P, na.rm = TRUE)
  )
}

# Import des données
csp_IRIS <- import_csp_departement_IRIS() %>%
  full_join(import_epci_COM(), by = "INSEE_COM") %>%
  full_join(import_departement_IRIS(), by = c("CODE_IRIS", "INSEE_COM"))

# Apply computations to geo levels
source("source/functions/apply_computations.R")
csp_stats <- apply_computations(
  csp_IRIS,
  compute_stats_csp,
  geo_levels
)

csp_stats %>%
  rename(
    " " = id,
    "1. Agri." = C17_POP15P_CS1,
    "2. Arti." = C17_POP15P_CS2,
    "3. CPIS" = C17_POP15P_CS3,
    "4. PI" = C17_POP15P_CS4,
    "5. Empl." = C17_POP15P_CS5,
    "6. Ouvr." = C17_POP15P_CS6,
    "7. Retr." = C17_POP15P_CS7,
    "8. Autres" = C17_POP15P_CS8
  ) %>%
  gt() %>%
  tab_header(
    title = "Catégories socio-professionnelles",
    subtitle = "Individus de 15 ans et plus"
  ) %>%
  fmt_percent(
    columns = c(2:9),
    decimals = 0,
    pattern = "{x}",
    incl_space = TRUE,
    locale = "fr_FR"
  ) %>%
  tab_source_note(
    source_note = "Données : Insee, 2017."
  )
```

```{r diplomes, echo=FALSE}
# Traitement à faire
compute_stats_dipl = function(data) {
  data %>% summarise(
    # Part de sans diplômes ou diplômés d'un BEPC
    P17_NSCOL15P_DIPLMINBEPC = sum(P17_NSCOL15P_DIPLMINBEPC, na.rm = TRUE) / sum(P17_NSCOL15P, na.rm = TRUE),
    # Part de diplômés d'un CAP/BEP
    P17_NSCOL15P_CAPBEP = sum(P17_NSCOL15P_CAPBEP, na.rm = TRUE) / sum(P17_NSCOL15P, na.rm = TRUE),
    # Part de diplômés du Bac
    P17_NSCOL15P_BAC = sum(P17_NSCOL15P_BAC, na.rm = TRUE) / sum(P17_NSCOL15P, na.rm = TRUE),
    # Part de diplômés du supérieur
    P17_NSCOL15P_SUP = sum(P17_NSCOL15P_SUP, na.rm = TRUE) / sum(P17_NSCOL15P, na.rm = TRUE)
  )
}

# Import des données
dipl_IRIS <- import_dipl_departement_IRIS() %>%
  full_join(import_epci_COM(), by = "INSEE_COM") %>%
  full_join(import_departement_IRIS(), by = c("CODE_IRIS", "INSEE_COM"))

# Apply computations to geo levels
source("source/functions/apply_computations.R")
dipl_stats <- apply_computations(
  dipl_IRIS,
  compute_stats_dipl,
  geo_levels
)

dipl_stats %>%
  rename(
    " " = id,
    "Sans diplôme ou BEPC" = P17_NSCOL15P_DIPLMINBEPC,
    "CAP ou BEP" = P17_NSCOL15P_CAPBEP,
    "Bac" = P17_NSCOL15P_BAC,
    "Enseignement sup." = P17_NSCOL15P_SUP
  ) %>%
  gt() %>%
  tab_header(
    title = "Niveaux de diplôme",
    subtitle = "Individus non-scolarisés de 15 ans et plus"
  ) %>%
  fmt_percent(
    columns = 2:5,
    decimals = 0,
    pattern = "{x}",
    incl_space = TRUE,
    locale = "fr_FR"
  ) %>%
  tab_source_note(
    source_note = "Données : Insee, 2017."
  )
```

```{r etudiants, echo=FALSE}
# Traitement à faire
compute_stats_etud = function(data) {
  data %>% summarise(
    # Part de scolarisés dans les 18-24 ans
    P17_SCOL1824_P = sum(P17_SCOL1824, na.rm = TRUE) / sum(P17_POP1824, na.rm = TRUE),
    # Nombre de scolarisés dans les 18-24 ans
    P17_SCOL1824_N = sum(P17_SCOL1824, na.rm = TRUE),
    # Part de scolarisés dans les 25-29 ans
    P17_SCOL2529_P = sum(P17_SCOL2529, na.rm = TRUE) / sum(P17_POP2529, na.rm = TRUE),
    # Nombre de scolarisés dans les 25-29 ans
    P17_SCOL2529_N = sum(P17_SCOL2529, na.rm = TRUE)
  )
}

# Import des données
etud_IRIS <- import_etud_departement_IRIS() %>%
  full_join(import_epci_COM(), by = "INSEE_COM") %>%
  full_join(import_departement_IRIS(), by = c("CODE_IRIS", "INSEE_COM"))

# Apply computations to geo levels
source("source/functions/apply_computations.R")
etud_stats <- apply_computations(
  etud_IRIS,
  compute_stats_etud,
  geo_levels
)

etud_stats %>%
  rename(
    " " = id
  ) %>%
  gt() %>%
  tab_header(title = "Étudiants", subtitle = md("&nbsp;")) %>%
  fmt_percent(
    columns = c(2, 4),
    decimals = 0,
    pattern = "{x}",
    incl_space = TRUE,
    locale = "fr_FR"
  ) %>%
  fmt_number(
    columns = c(3, 5),
    decimals = 0,
    locale = "fr_FR"
  ) %>%
  tab_spanner(
    label = "18-24 ans",
    columns = 2:3
  ) %>%
  tab_spanner(
    label = "25-29 ans",
    columns = 4:5
  ) %>%
  cols_label(
    P17_SCOL1824_P = "Part",
    P17_SCOL1824_N = "Nombre",
    P17_SCOL2529_P = "Part",
    P17_SCOL2529_N = "Nombre"
  ) %>%
  tab_source_note(
    source_note = "Données : Insee, 2017."
  )
```

## Export

Les résultats sont exportés dans le fichier `results/diag_stats.xlsx`.

```{r excel_export, include=FALSE}
library(openxlsx)
tables_to_export <- list(
  "DEMOGRAPHIE" = demog_stats,
  "CSP" = csp_stats,
  "DIPLOMES" = dipl_stats,
  "ETUDIANTS" = etud_stats
)
write.xlsx(
  tables_to_export,
  file = "results/diag_stats.xlsx",
  borders = "all"
)
```
